name: Test
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.run/**'
      - '.editorconfig'
      - '*ignore'
      - 'Taskfile.*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.run/**'
      - '.editorconfig'
      - '*ignore'
      - 'Taskfile.*'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ "stable", "oldstable", 1.21.x, 1.20.x, 1.19.x, 1.18.x, 1.17.x ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -race -v
